src:
  - astroturf
  - kevin_feedback
  - botwiki
  - zoher-organization
  - cresci-17
  - rtbust
  - stock
  - gilani-17
  - midterm-2018
  - josh_political
  - pronbots
  - varol-icwsm
  - gregory_purchased
  - verified

retraining_dataset : "dataset/retraining_data"

segmentation_type: "sets_of_four"
comparison_method: "cumulative"
distance_metric: "compression"

n_gram: 4
min_tweets_per_user: 20
max_tweets_per_user: 300

# gen_bloc_params :  {
#   'blank_mark': 60, 
#   'bloc_alphabets': ['action', 'content_syntactic'], 
#   'fold_start_count': 10,  
#   'keep_bloc_segments': True, 
#   'keep_tweets': True, 
#   'segmentation_type': 'week_number', #['week_number', 'day_of_year_bin', 'yyyy-mm-dd', 'segment_on_pauses']
#   'sort_action_words': False, 
#   'tweet_order': 'sorted'
# }

gen_bloc_params : {
  'blank_mark': 60, 
  'bloc_alphabets': ['action', 'content_syntactic'], 
  'fold_start_count': 10, 
  'keep_bloc_segments': True, 
  'keep_tweets': True, 
  'segmentation_type': 'segment_on_pauses',
  'segment_on_pauses': 3600, 
  'sort_action_words': False, 
  'tweet_order': 'sorted'
}

bloc_variant : {'type': 'folded_words', 'fold_start_count': 3, 'count_applies_to_all_char': False}
bloc_params_tf : {'ngram': 1, 'min_df': 1, 'tf_matrix_norm': '', 'keep_tf_matrix': True, 'set_top_ngrams': True, 'top_ngrams_add_all_docs': False, 'token_pattern': '[^□⚀⚁⚂⚃⚄⚅. |()*]+|[□⚀⚁⚂⚃⚄⚅.]'}