path_to_data : "/sciclone/data10/iahewababarand/behavior_change/behavioral-change/data/users/celebrity_elonmusk.jsonl.gz"

segmentation_type: "sets_of_four"
comparison_method: "cumulative"
distance_metric: "cosine-similarity"
n_gram: 4

gen_bloc_params : {
  'blank_mark': 60, 
  'bloc_alphabets': ['action', 'content_syntactic'], 
  'fold_start_count': 10, 
  'keep_bloc_segments': True, 
  'keep_tweets': True, 
  'segmentation_type': 'segment_on_pauses',
  'segment_on_pauses': 3600, 
  'sort_action_words': False, 
  'tweet_order': 'sorted'
}

bloc_variant : {'type': 'folded_words', 'fold_start_count': 3, 'count_applies_to_all_char': False}
bloc_params_tf : {'ngram': 1, 'min_df': 1, 'tf_matrix_norm': '', 'keep_tf_matrix': True, 'set_top_ngrams': True, 'top_ngrams_add_all_docs': False, 'token_pattern': '[^□⚀⚁⚂⚃⚄⚅. |()*]+|[□⚀⚁⚂⚃⚄⚅.]'}